"""
AI-Powered Protocol Generator
Generates experimental protocols using template-based AI approach
"""

import streamlit as st
from datetime import datetime

def generate_protocol(design: dict, protocol_type: str = "comprehensive") -> str:
    """
    Generate experimental protocol based on nanoparticle design
    
    Parameters:
    -----------
    design : dict
        Nanoparticle design parameters
    protocol_type : str
        Type of protocol to generate
    
    Returns:
    --------
    protocol : str
        Generated protocol text
    """
    
    current_date = datetime.now().strftime("%B %d, %Y")
    
    # Extract key parameters
    name = design['name']
    material = design['material']
    size = design['size']
    charge = design['charge']
    ligand = design['ligand']
    payload = design['payload']
    loading = design['payload_amount']
    target = design['target']
    dose = design['dose']
    pdi = design['pdi']
    
    protocol = f"""
================================================================================
EXPERIMENTAL PROTOCOL: {name}
================================================================================

Generated by: NanoBio Studio (AI-Assisted Protocol Generator)
Date: {current_date}
Protocol Version: 1.0

================================================================================
1. FORMULATION OVERVIEW
================================================================================

Formulation ID: {name}
Nanoparticle Type: {material}
Target Tissue: {target}
Therapeutic Payload: {payload}

Key Specifications:
- Target Size: {size:.1f} nm (±10%)
- Target Zeta Potential: {charge:.1f} mV
- Surface Modification: {ligand}
- Payload Loading: {loading:.1f}% (w/w)
- Polydispersity Index (PDI): <{pdi:.2f}
- Intended Dose: {dose:.2f} mg/kg body weight

================================================================================
2. MATERIALS AND REAGENTS
================================================================================

2.1 Core Nanoparticle Materials
{generate_material_section(material)}

2.2 Surface Modification Reagents
{generate_ligand_section(ligand)}

2.3 Therapeutic Payload
{generate_payload_section(payload)}

2.4 Buffers and Solvents
- Phosphate Buffered Saline (PBS), pH 7.4, sterile
- Ultrapure water (Milli-Q, 18.2 MΩ·cm)
- Ethanol (200 proof, molecular biology grade)
- {get_additional_solvents(material)}

2.5 Equipment
- Sonicator (probe or bath type)
- High-speed centrifuge (capable of 20,000 × g)
- Dynamic Light Scattering (DLS) instrument
- Zeta potential analyzer
- UV-Vis spectrophotometer
- {get_specific_equipment(material)}

================================================================================
3. SYNTHESIS PROTOCOL
================================================================================

3.1 Preparation Phase
{generate_prep_phase(material, size)}

3.2 Nanoparticle Formation
{generate_synthesis_method(material, size, charge)}

3.3 Surface Functionalization
{generate_functionalization(ligand, material)}

3.4 Payload Loading
{generate_loading_method(payload, material, loading)}

3.5 Purification
{generate_purification_method(material)}

================================================================================
4. CHARACTERIZATION PROTOCOL
================================================================================

4.1 Size and Morphology
□ Dynamic Light Scattering (DLS)
  - Measure hydrodynamic diameter (target: {size:.1f} ± {size*0.1:.1f} nm)
  - Determine polydispersity index (target: PDI < {pdi:.2f})
  - Repeat measurements in triplicate
  - Temperature: 25°C
  
□ Transmission Electron Microscopy (TEM)
  - Prepare samples on carbon-coated copper grids
  - Staining: {get_tem_stain(material)}
  - Measure at least 100 particles for size distribution
  - Assess morphology and aggregation state

4.2 Surface Properties
□ Zeta Potential
  - Measure in PBS pH 7.4
  - Target: {charge:.1f} ± {abs(charge)*0.2:.1f} mV
  - Triplicate measurements

□ Surface Chemistry Verification
  {get_surface_verification(ligand)}

4.3 Payload Characterization
□ Loading Efficiency
  {get_loading_verification(payload, material)}

□ Encapsulation Efficiency
  - Calculate as: (payload encapsulated / total payload added) × 100%
  - Target: >{max(70, loading):.0f}%

4.4 Stability Studies
□ Storage Stability
  - Store at 4°C, -20°C, and -80°C
  - Measure size and PDI at 0, 7, 14, 30 days
  
□ Serum Stability
  - Incubate in 10% FBS at 37°C
  - Monitor size and aggregation over 24h

================================================================================
5. IN VITRO STUDIES
================================================================================

5.1 Cell Viability Assay
□ Cell Line: {get_cell_line(target)}
□ Assay: MTT or MTS assay
□ Concentration Range: 0.1 - 100 μg/mL
□ Incubation: 24h, 48h, 72h
□ Controls: Untreated cells, vehicle control

5.2 Cellular Uptake
□ Method: Flow cytometry or confocal microscopy
□ Fluorescent Labeling: {get_label_method(material)}
□ Time Points: 1h, 4h, 24h
□ Temperature: 37°C, 4°C (to assess active vs. passive uptake)

5.3 Therapeutic Efficacy (if applicable)
{generate_efficacy_assay(payload, target)}

5.4 Toxicity Assessment
□ LDH Release Assay (membrane integrity)
□ ROS Generation Assay
□ Apoptosis/Necrosis Assay (Annexin V/PI staining)

================================================================================
6. IN VIVO STUDIES (if applicable)
================================================================================

⚠️ All animal studies must be approved by Institutional Animal Care and Use Committee (IACUC)

6.1 Animal Model
- Species: {get_animal_model(target)}
- Strain: To be determined based on target indication
- Age: 6-8 weeks
- Number: Minimum 5 per group (power analysis recommended)

6.2 Administration
- Route: {get_administration_route(target, material)}
- Dose: {dose:.2f} mg/kg body weight
- Vehicle: Sterile PBS or saline
- Frequency: Single dose or as per study design

6.3 Pharmacokinetics
□ Blood Collection: 0, 0.5h, 1h, 2h, 4h, 8h, 24h, 48h
□ Tissue Collection: Liver, spleen, kidney, lung, tumor (if applicable) at 24h
□ Analysis: {get_pk_analysis_method(payload)}

6.4 Biodistribution
□ Imaging: {get_imaging_method(material, payload)}
□ Quantification: ICP-MS, fluorescence, or radiolabel counting

6.5 Efficacy Assessment
{generate_invivo_efficacy(target, payload)}

6.6 Toxicity Studies
□ Body weight monitoring
□ Clinical observations
□ Blood chemistry (liver and kidney function)
□ Complete blood count (CBC)
□ Histopathology of major organs

================================================================================
7. SAFETY AND DISPOSAL
================================================================================

7.1 Safety Precautions
{generate_safety_warnings(material, payload)}

7.2 Waste Disposal
{generate_disposal_instructions(material, payload)}

================================================================================
8. DATA ANALYSIS AND REPORTING
================================================================================

8.1 Statistical Analysis
- Software: GraphPad Prism, SPSS, or R
- Tests: One-way ANOVA with post-hoc tests, t-tests as appropriate
- Significance: p < 0.05
- Data presentation: Mean ± SD or SEM (specify, n ≥ 3)

8.2 Quality Control Criteria
✓ Size: {size:.1f} ± {size*0.1:.1f} nm
✓ PDI: < {pdi:.2f}
✓ Zeta potential: {charge:.1f} ± {abs(charge)*0.2:.1f} mV
✓ Encapsulation efficiency: > 70%
✓ Batch-to-batch variability: < 10% RSD

8.3 Documentation
- Maintain detailed laboratory notebook
- Record all deviations from protocol
- Archive samples at -80°C for at least 2 years
- Photograph TEM images and DLS traces

================================================================================
9. REFERENCES AND RESOURCES
================================================================================

Key Literature:
1. Relevant nanomedicine review articles
2. Material-specific synthesis protocols
3. Target tissue biology and pathology
4. Regulatory guidelines (FDA, EMA)

Recommended Reading:
- Nature Nanotechnology
- ACS Nano
- Journal of Controlled Release
- Advanced Drug Delivery Reviews

================================================================================
10. PROTOCOL NOTES AND TROUBLESHOOTING
================================================================================

Common Issues and Solutions:
{generate_troubleshooting(material, size, charge)}

Critical Success Factors:
✓ Strict control of pH and ionic strength
✓ Temperature control during synthesis
✓ Proper storage conditions
✓ Regular equipment calibration
✓ Aseptic technique for biological studies

================================================================================
END OF PROTOCOL
================================================================================

Generated by NanoBio Studio
Experts Group FZE
Email: info@expertsgroup.me
Website: https://www.expertsgroup.me

DISCLAIMER: This protocol is generated for research and educational purposes.
Optimize and validate all procedures for your specific laboratory conditions.
Ensure compliance with institutional safety and ethical guidelines.

================================================================================
"""
    
    return protocol

def generate_material_section(material: str) -> str:
    """Generate material-specific reagents section"""
    material_lower = material.lower()
    
    if "lipid" in material_lower or "liposome" in material_lower:
        return """- Ionizable lipid (e.g., DLin-MC3-DMA, SM-102)
- Phospholipid (e.g., DSPC, DOPC)
- Cholesterol (high purity, >99%)
- PEG-lipid (e.g., DMG-PEG2000)
- Chloroform or ethanol for lipid dissolution"""
    
    elif "gold" in material_lower:
        return """- Gold(III) chloride trihydrate (HAuCl4·3H2O)
- Sodium citrate tribasic dihydrate
- Sodium borohydride (for smaller particles)
- Trisodium citrate (for larger particles)
- Ultrapure water"""
    
    elif "plga" in material_lower or "polymer" in material_lower:
        return """- PLGA polymer (specify MW and lactide:glycolide ratio, e.g., 50:50, 75:25)
- Dichloromethane (DCM) or acetone
- Polyvinyl alcohol (PVA) or Pluronic F127 as stabilizer
- Organic solvents for polymer dissolution"""
    
    elif "silica" in material_lower:
        return """- Tetraethyl orthosilicate (TEOS)
- Cetyltrimethylammonium bromide (CTAB) - for mesoporous silica
- Sodium hydroxide (NaOH)
- Ethanol (absolute)
- Ammonium hydroxide"""
    
    else:
        return """- Core nanoparticle material (as specified)
- Appropriate solvents for dissolution/dispersion
- Stabilizing agents
- Reducing agents (if applicable)"""

def generate_ligand_section(ligand: str) -> str:
    """Generate ligand-specific section"""
    ligand_lower = ligand.lower()
    
    if "peg" in ligand_lower:
        return """- PEG or PEG-derivative (MW 2000-5000 Da recommended)
- Coupling reagent: EDC/NHS or maleimide chemistry
- Reaction buffer (pH 7.4-8.0)"""
    
    elif "antibody" in ligand_lower or "mab" in ligand_lower:
        return """- Monoclonal antibody (specify clone and supplier)
- Coupling reagent: EDC/sulfo-NHS or SPDP
- Conjugation buffer (PBS, pH 7.2)
- Antibody purification/dialysis equipment"""
    
    elif "peptide" in ligand_lower or "rgd" in ligand_lower:
        return """- Targeting peptide (custom synthesis, >95% purity)
- HPLC-grade solvents for peptide dissolution
- Coupling chemistry reagents
- Protecting groups if needed"""
    
    elif "folate" in ligand_lower:
        return """- Folic acid or folate-PEG conjugate
- Carbodiimide coupling reagents (EDC/NHS)
- DMSO for folate dissolution"""
    
    else:
        return """- Surface ligand or targeting moiety
- Appropriate coupling chemistry reagents
- Purification materials"""

def generate_payload_section(payload: str) -> str:
    """Generate payload-specific section"""
    payload_lower = payload.lower()
    
    if "mrna" in payload_lower:
        return """- mRNA (in vitro transcribed, capped, poly(A)-tailed)
- RNase-free water and buffers
- RNase inhibitor
- Storage: -80°C in single-use aliquots"""
    
    elif "sirna" in payload_lower:
        return """- siRNA duplex (chemically synthesized, HPLC-purified)
- RNase-free TE buffer or PBS
- Store at -20°C"""
    
    elif "dna" in payload_lower or "plasmid" in payload_lower:
        return """- Plasmid DNA (endotoxin-free preparation)
- TE buffer (10 mM Tris, 1 mM EDTA, pH 8.0)
- DNase-free equipment and reagents"""
    
    elif "crispr" in payload_lower:
        return """- Cas9 protein or mRNA
- Guide RNA (gRNA)
- Cas9-gRNA RNP complex formation buffer
- RNase-free conditions"""
    
    elif "small molecule" in payload_lower:
        return """- Drug compound (specify purity and source)
- Appropriate solvent (DMSO, ethanol, or aqueous)
- Standard curve materials for quantification"""
    
    else:
        return """- Therapeutic or diagnostic payload
- Appropriate storage buffer
- Stability-maintaining conditions"""

def get_additional_solvents(material: str) -> str:
    """Get material-specific solvents"""
    if "lipid" in material.lower():
        return "Chloroform, methanol, tertiary butanol (for freeze-drying)"
    elif "polymer" in material.lower():
        return "Dichloromethane (DCM), acetone, ethyl acetate"
    else:
        return "Appropriate organic solvents as needed"

def get_specific_equipment(material: str) -> str:
    """Get material-specific equipment"""
    material_lower = material.lower()
    
    if "lipid" in material_lower:
        return "Microfluidic mixer or thin-film hydration apparatus, extruder (for LUVs)"
    elif "gold" in material_lower:
        return "Heating mantle, magnetic stirrer with hotplate"
    elif "polymer" in material_lower:
        return "Homogenizer, rotary evaporator"
    elif "exosome" in material_lower:
        return "Ultracentrifuge, filtration units (0.22 μm)"
    else:
        return "Standard synthesis equipment"

def generate_prep_phase(material: str, size: float) -> str:
    """Generate preparation phase instructions"""
    return f"""Step 1: Clean all glassware with aqua regia or piranha solution
Step 2: Rinse thoroughly with ultrapure water
Step 3: Prepare all reagents and verify concentrations
Step 4: Set up workspace with appropriate safety equipment
Step 5: Pre-chill or pre-heat equipment as needed
Step 6: Calculate reagent amounts for target size of {size:.1f} nm

⚠️ All procedures should be performed in a clean room or laminar flow hood when possible."""

def generate_synthesis_method(material: str, size: float, charge: float) -> str:
    """Generate synthesis method based on material type"""
    material_lower = material.lower()
    
    if "lipid" in material_lower:
        return f"""Method: Microfluidic Mixing or Thin-Film Hydration

Option A - Microfluidic Mixing:
1. Prepare lipid solution in ethanol (total lipid: 10-50 mM)
2. Prepare aqueous phase (PBS or citrate buffer, pH 4-5)
3. Mix at flow rate ratio 3:1 (aqueous:organic) using microfluidic device
4. Collect lipid nanoparticles
5. Target size: {size:.1f} nm (adjust flow rates to control size)

Option B - Thin-Film Hydration:
1. Dissolve lipids in chloroform (total: 10-20 mg)
2. Evaporate solvent using rotary evaporator to form thin film
3. Hydrate with PBS at 60°C for 30 min with gentle agitation
4. Extrude through polycarbonate membranes (pore size: {int(size*1.2)} nm)
5. Pass through 5-11 times for uniform size distribution

Adjust lipid ratios to achieve target charge of {charge:.1f} mV"""
    
    elif "gold" in material_lower:
        if size < 20:
            return f"""Method: Sodium Borohydride Reduction (for small particles <20 nm)

1. Prepare 0.25 mM HAuCl4 solution in ultrapure water (100 mL)
2. Cool to 4°C on ice bath
3. Prepare fresh 0.1 M NaBH4 solution
4. Add NaBH4 drop-wise with vigorous stirring
5. Stir for 2h at 4°C
6. Bring to room temperature
7. Expected size: {size:.1f} nm
8. Color should be dark brown-red

Size control: Adjust NaBH4 concentration"""
        else:
            return f"""Method: Citrate Reduction (Turkevich method for 10-150 nm particles)

1. Heat 100 mL of ultrapure water to boiling
2. Add 1 mL of 1% HAuCl4 solution
3. Add 10 mL of 1% sodium citrate solution rapidly
4. Continue boiling for 15-30 min
5. Cool to room temperature
6. Expected size: {size:.1f} nm
7. Color: ruby red for ~20nm, blue-purple for larger particles

Size control: Vary citrate:gold ratio (higher citrate = smaller particles)"""
    
    elif "plga" in material_lower or "polymer" in material_lower:
        return f"""Method: Single Emulsion (O/W) or Double Emulsion (W/O/W)

Single Emulsion:
1. Dissolve PLGA (100 mg) in DCM or acetone (2 mL)
2. Add to aqueous PVA solution (1% w/v, 10 mL)
3. Sonicate or homogenize to form emulsion
4. Evaporate organic solvent under reduced pressure or stirring overnight
5. Collect particles by centrifugation (20,000 × g, 30 min)
6. Wash 3× with ultrapure water
7. Target size: {size:.1f} nm

Size control:
- Sonication power and duration
- PLGA concentration
- Organic:aqueous phase ratio
- Homogenization speed"""
    
    elif "silica" in material_lower:
        return f"""Method: Stöber Process (for dense silica) or Surfactant-Templated (for mesoporous)

Dense Silica (Stöber):
1. Mix ethanol (40 mL), water (10 mL), and NH4OH (1-5 mL)
2. Add TEOS (2-10 mL) dropwise under stirring
3. Stir at room temperature for 2-24h
4. Collect by centrifugation
5. Wash with ethanol and water
6. Target size: {size:.1f} nm

Size control: Adjust NH4OH and water concentrations

Mesoporous Silica (MSN):
1. Dissolve CTAB (0.5 g) in water (240 mL) and NaOH (1.75 mL, 2M)
2. Heat to 80°C
3. Add TEOS (2.5 mL) dropwise
4. Stir for 2h at 80°C
5. Cool, collect, wash
6. Remove template by calcination (550°C, 6h) or solvent extraction"""
    
    else:
        return f"""Generic Synthesis Protocol:
1. Prepare precursor materials in appropriate solvent
2. Control nucleation and growth phases
3. Add stabilizing agents
4. Monitor size formation
5. Target size: {size:.1f} nm
6. Adjust conditions for size control

Refer to material-specific literature for detailed synthesis procedures."""

def generate_functionalization(ligand: str, material: str) -> str:
    """Generate surface functionalization protocol"""
    ligand_lower = ligand.lower()
    
    if "peg" in ligand_lower:
        return """PEGylation Protocol:
1. Disperse nanoparticles in PBS pH 7.4
2. Add PEG-NHS or maleimide-PEG (molar ratio 1:1000 to 1:10000 particle:PEG)
3. React for 2-4h at room temperature with gentle mixing
4. Purify by dialysis or centrifugation to remove excess PEG
5. Verify PEGylation by DLS (increase in size) and zeta potential change
6. Quantify PEG density by colorimetric assay or NMR"""
    
    elif "none" in ligand_lower:
        return """No surface modification required.
Ensure particles are stable in intended storage buffer."""
    
    else:
        return f"""Surface Modification with {ligand}:
1. Activate nanoparticle surface (if needed)
2. Dissolve {ligand} in appropriate buffer
3. Add to nanoparticle suspension
4. React under optimized conditions (pH, temperature, time)
5. Quench reaction if needed
6. Purify by size exclusion or dialysis
7. Verify conjugation by relevant analytical method
8. Quantify ligand density"""

def generate_loading_method(payload: str, material: str, loading: float) -> str:
    """Generate payload loading protocol"""
    payload_lower = payload.lower()
    material_lower = material.lower()
    
    if "none" in payload_lower:
        return "No payload loading required for this formulation."
    
    if "lipid" in material_lower:
        if "rna" in payload_lower or "dna" in payload_lower:
            return f"""Nucleic Acid Loading (for lipid nanoparticles):
Method: Co-formulation during synthesis
1. Dissolve RNA/DNA in aqueous buffer (pH 4-5 citrate or acetate)
2. Mix with lipid nanoparticles during synthesis (microfluidic or bulk mixing)
3. Target N/P ratio: 3-10 (positive:negative charge ratio)
4. Target loading: {loading:.1f}% w/w
5. Purify to remove unencapsulated nucleic acid
6. Quantify encapsulation by RiboGreen or PicoGreen assay

Encapsulation efficiency = (RNA in particles / total RNA) × 100%
Target: >80%"""
        
    if "polymer" in material_lower or "plga" in material_lower:
        if "small molecule" in payload_lower or "protein" in payload_lower:
            return f"""Payload Loading (PLGA nanoparticles):
Method: Emulsion with payload in organic or aqueous phase
1. For hydrophobic drugs: Dissolve in DCM with PLGA
2. For hydrophilic drugs/proteins: Use W/O/W double emulsion
3. Target drug:polymer ratio for {loading:.1f}% loading: Calculate accordingly
4. Encapsulate during nanoparticle formation
5. Measure loading by extracting particles and quantifying by HPLC/UV-Vis
6. Calculate: Loading (%) = (mass of drug in NPs / mass of NPs) × 100%"""
    
    return f"""Payload Loading Protocol:
1. Determine optimal loading method based on payload properties
2. Mix payload with nanoparticles or include during synthesis
3. Optimize loading conditions (pH, temperature, ratios)
4. Target loading: {loading:.1f}% w/w
5. Purify to remove free payload
6. Quantify loading efficiency
7. Confirm payload stability and activity"""

def generate_purification_method(material: str) -> str:
    """Generate purification protocol"""
    return """Purification Steps:
1. Remove large aggregates: Centrifuge at low speed (500 × g, 5 min)
2. Collect supernatant
3. Remove unencapsulated materials:
   - Option A: Centrifugation (20,000 × g, 30 min)
   - Option B: Size exclusion chromatography (Sepharose CL-4B)
   - Option C: Dialysis (MWCO 100-300 kDa)
   - Option D: Ultrafiltration (100 kDa cutoff)
4. Wash 2-3 times with PBS or storage buffer
5. Resuspend in final buffer
6. Filter through 0.22 μm filter for sterility (if needed)
7. Store at 4°C (short-term) or -80°C (long-term) with cryoprotectant"""

def get_tem_stain(material: str) -> str:
    """Get TEM staining method"""
    if "lipid" in material.lower():
        return "Uranyl acetate (2% w/v) or phosphotungstic acid"
    else:
        return "Uranyl acetate (2% w/v) or lead citrate"

def get_surface_verification(ligand: str) -> str:
    """Get surface verification methods"""
    ligand_lower = ligand.lower()
    
    if "peg" in ligand_lower:
        return """- FTIR: Verify C-O-C stretching peaks
- NMR: Quantify PEG density
- XPS: Surface elemental analysis"""
    elif "antibody" in ligand_lower:
        return """- ELISA or Western blot for antibody presence
- BCA assay for protein quantification
- Flow cytometry for binding verification"""
    else:
        return """- FTIR or Raman spectroscopy
- Surface plasmon resonance (SPR)
- XPS or elemental analysis"""

def get_loading_verification(payload: str, material: str) -> str:
    """Get loading verification method"""
    payload_lower = payload.lower()
    
    if "mrna" in payload_lower or "sirna" in payload_lower:
        return """- RiboGreen assay for RNA quantification
- RT-qPCR for specific sequence detection
- Gel electrophoresis for integrity"""
    elif "dna" in payload_lower:
        return """- PicoGreen or Quant-iT assay
- UV-Vis at 260 nm
- Agarose gel electrophoresis"""
    elif "small molecule" in payload_lower:
        return """- HPLC with UV/fluorescence detection
- UV-Vis spectroscopy
- Mass spectrometry"""
    elif "protein" in payload_lower:
        return """- BCA or Bradford assay
- SDS-PAGE
- Western blot for specific protein"""
    else:
        return """- Appropriate analytical method based on payload properties
- Standard curve for quantification
- Mass balance calculation"""

def get_cell_line(target: str) -> str:
    """Get appropriate cell line based on target"""
    target_lower = target.lower()
    
    if "tumor" in target_lower or "cancer" in target_lower:
        return "Cancer cell line relevant to target (e.g., HeLa, MCF-7, A549, HT-29)"
    elif "liver" in target_lower:
        return "Hepatocyte cell line (e.g., HepG2, Hep3B)"
    elif "brain" in target_lower:
        return "Neuronal or glial cell line (e.g., SH-SY5Y, U87-MG)"
    elif "lung" in target_lower:
        return "Lung cell line (e.g., A549, H1299)"
    else:
        return "Cell line relevant to target tissue"

def get_label_method(material: str) -> str:
    """Get fluorescent labeling method"""
    if "lipid" in material.lower():
        return "DiI, DiO, or rhodamine-PE"
    elif "gold" in material.lower():
        return "Intrinsic fluorescence or conjugated fluorophore"
    else:
        return "FITC, rhodamine, or Cy5 conjugation"

def generate_efficacy_assay(payload: str, target: str) -> str:
    """Generate efficacy assay description"""
    payload_lower = payload.lower()
    
    if "sirna" in payload_lower or "mrna" in payload_lower:
        return """Gene Expression Analysis:
□ RT-qPCR for target gene expression
□ Western blot for protein knockdown/expression
□ Functional assays specific to target pathway"""
    elif "crispr" in payload_lower:
        return """Gene Editing Efficiency:
□ T7 endonuclease I assay for indels
□ Next-generation sequencing for editing verification
□ Functional validation of edited phenotype"""
    elif "drug" in payload_lower or "small molecule" in payload_lower:
        return """Drug Efficacy Assessment:
□ Cell viability/proliferation assay
□ Target-specific functional assay
□ Dose-response curve (IC50 determination)"""
    else:
        return """Functional Efficacy Studies:
□ Target-specific bioassays
□ Dose-response relationships
□ Time-course studies"""

def get_animal_model(target: str) -> str:
    """Get animal model recommendation"""
    target_lower = target.lower()
    
    if "tumor" in target_lower:
        return "Mice (immunocompetent or immunodeficient, depending on tumor model)"
    elif "brain" in target_lower:
        return "Mice or rats (consider BBB penetration challenges)"
    else:
        return "Mice or rats (select based on target similarity to humans)"

def get_administration_route(target: str, material: str) -> str:
    """Get administration route"""
    target_lower = target.lower()
    
    if "tumor" in target_lower:
        return "Intravenous (tail vein), intratumoral, or intraperitoneal"
    elif "brain" in target_lower:
        return "Intravenous or intranasal (for BBB penetration)"
    elif "lung" in target_lower:
        return "Intravenous, intratracheal, or inhalation"
    elif "skin" in target_lower:
        return "Topical or subcutaneous"
    else:
        return "Intravenous (most common) or route relevant to target"

def get_pk_analysis_method(payload: str) -> str:
    """Get PK analysis method"""
    payload_lower = payload.lower()
    
    if "rna" in payload_lower or "dna" in payload_lower:
        return "qPCR for nucleic acid quantification in tissues"
    elif "protein" in payload_lower:
        return "ELISA or Western blot"
    else:
        return "HPLC, LC-MS/MS, or ICP-MS (for metal-based NPs)"

def get_imaging_method(material: str, payload: str) -> str:
    """Get imaging method"""
    material_lower = material.lower()
    
    if "gold" in material_lower:
        return "CT imaging, photoacoustic imaging, or dark-field microscopy"
    elif "quantum" in material_lower:
        return "Fluorescence imaging (in vivo imaging system)"
    elif "iron" in material_lower or "magnetic" in material_lower:
        return "MRI imaging"
    else:
        return "Fluorescence imaging (with labeled particles) or radiolabeling"

def generate_invivo_efficacy(target: str, payload: str) -> str:
    """Generate in vivo efficacy assessment"""
    target_lower = target.lower()
    
    if "tumor" in target_lower:
        return """Tumor Efficacy Assessment:
□ Tumor volume measurement (caliper, 2-3× per week)
□ Bioluminescence imaging (if using luciferase-tagged cells)
□ Survival analysis (Kaplan-Meier)
□ Immunohistochemistry of tumor tissue
□ Target biomarker expression"""
    elif "inflammation" in target_lower or "arthritis" in target_lower:
        return """Anti-Inflammatory Efficacy:
□ Joint swelling measurement
□ Cytokine levels (ELISA from serum/tissue)
□ Histological assessment of inflammation
□ Pain/mobility assessment (if applicable)"""
    else:
        return """Disease-Specific Efficacy Assessment:
□ Define relevant biomarkers
□ Quantify target tissue response
□ Compare to untreated and positive controls
□ Statistical analysis of treatment groups"""

def generate_safety_warnings(material: str, payload: str) -> str:
    """Generate safety warnings"""
    material_lower = material.lower()
    payload_lower = payload.lower()
    
    warnings = []
    
    if "gold" in material_lower or "metal" in material_lower:
        warnings.append("• Metal nanoparticles: Use appropriate PPE, dispose as hazardous waste")
    
    if "quantum" in material_lower:
        warnings.append("• Quantum dots contain heavy metals (Cd, Se) - handle as toxic materials")
    
    if "rna" in payload_lower or "dna" in payload_lower:
        warnings.append("• RNA/DNA: RNase/DNase-free techniques required, proper biohazard disposal")
    
    if "crispr" in payload_lower:
        warnings.append("• CRISPR materials: Follow institutional biosafety guidelines, BSL-2 minimum")
    
    warnings.append("• Wear lab coat, gloves, and eye protection at all times")
    warnings.append("• Work in fume hood when handling organic solvents")
    warnings.append("• Follow MSDS guidelines for all chemicals")
    
    return "\n".join(warnings)

def generate_disposal_instructions(material: str, payload: str) -> str:
    """Generate waste disposal instructions"""
    return """Waste Disposal Guidelines:
• Organic solvents: Collect in designated hazardous waste containers
• Aqueous waste: Neutralize and dispose according to local regulations
• Nanomaterial waste: Inactivate/solidify before disposal, follow EHS guidelines
• Biological waste: Autoclave before disposal
• Sharps: Use designated sharps containers
• Animal carcasses: Follow institutional IACUC disposal protocols

Contact your Environmental Health and Safety office for specific guidance."""

def generate_troubleshooting(material: str, size: float, charge: float) -> str:
    """Generate troubleshooting guide"""
    return f"""Problem: Particle size too large (>{size*1.2:.1f} nm)
Solution: Increase sonication power/time, adjust precursor ratios, optimize synthesis temperature

Problem: High polydispersity (PDI >{0.3})
Solution: Improve mixing efficiency, filter large aggregates, optimize synthesis kinetics, use extrusion

Problem: Particle aggregation
Solution: Optimize surface charge (target |ζ| >20 mV), add stabilizers, adjust ionic strength, improve PEGylation

Problem: Low encapsulation efficiency (<50%)
Solution: Optimize payload:carrier ratio, adjust pH, modify loading method, improve purification

Problem: Zeta potential off-target
Solution: Adjust ligand density, modify pH, change buffer composition

Problem: Poor batch-to-batch reproducibility
Solution: Standardize mixing speeds, control temperature strictly, use freshly prepared reagents, calibrate equipment

Problem: Instability during storage
Solution: Add cryoprotectant (trehalose, sucrose), optimize buffer conditions, store at -80°C, lyophilize"""

def show():
    """Display protocol generator interface"""
    st.title("📝 Protocol Generator")
    st.markdown("Generate comprehensive experimental protocols with AI assistance")
    
    st.markdown("---")
    
    # Display current design
    with st.expander("📋 Current Design Parameters", expanded=False):
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            st.metric("Formulation", st.session_state.design['name'])
            st.metric("Material", st.session_state.design['material'].split('(')[0].strip())
        
        with col2:
            st.metric("Size", f"{st.session_state.design['size']:.1f} nm")
            st.metric("Charge", f"{st.session_state.design['charge']:.1f} mV")
        
        with col3:
            st.metric("Ligand", st.session_state.design['ligand'].split('(')[0].strip())
            st.metric("Payload", st.session_state.design['payload'])
        
        with col4:
            st.metric("Target", st.session_state.design['target'])
            st.metric("Dose", f"{st.session_state.design['dose']:.1f} mg/kg")
    
    st.markdown("---")
    
    # Protocol options
    st.subheader("⚙️ Protocol Configuration")
    
    col1, col2 = st.columns(2)
    
    with col1:
        protocol_type = st.selectbox(
            "Protocol Type",
            [
                "Comprehensive (Full Detail)",
                "Synthesis Only",
                "Characterization Only",
                "In Vitro Testing",
                "In Vivo Studies"
            ],
            help="Select the scope of the protocol"
        )
    
    with col2:
        include_ai_suggestions = st.checkbox(
            "Include AI Optimization Suggestions",
            value=True,
            help="Add AI-generated optimization tips and best practices"
        )
    
    st.markdown("---")
    
    # Generate protocol
    col_gen1, col_gen2, col_gen3 = st.columns([1, 1, 1])
    
    with col_gen2:
        if st.button("🤖 Generate Protocol", type="primary", use_container_width=True):
            with st.spinner("Generating comprehensive protocol with AI assistance..."):
                import time
                time.sleep(1)  # Simulate AI processing
                
                protocol_text = generate_protocol(st.session_state.design, protocol_type)
                
                st.session_state.generated_protocol = protocol_text
                st.success("✅ Protocol generated successfully!")
                st.balloons()
    
    st.markdown("---")
    
    # Display generated protocol
    if hasattr(st.session_state, 'generated_protocol') and st.session_state.generated_protocol:
        st.subheader("📄 Generated Protocol")
        
        # Display in text area
        st.text_area(
            "Protocol Content",
            st.session_state.generated_protocol,
            height=400,
            help="Scroll to view full protocol"
        )
        
        st.markdown("---")
        
        # Download options
        st.subheader("💾 Download Protocol")
        
        col_dl1, col_dl2, col_dl3 = st.columns(3)
        
        with col_dl1:
            st.download_button(
                label="📥 Download as TXT",
                data=st.session_state.generated_protocol,
                file_name=f"{st.session_state.design['name']}_protocol.txt",
                mime="text/plain",
                use_container_width=True
            )
        
        with col_dl2:
            # Create a simple markdown version
            protocol_md = st.session_state.generated_protocol.replace("================================================================================", "---")
            
            st.download_button(
                label="📥 Download as Markdown",
                data=protocol_md,
                file_name=f"{st.session_state.design['name']}_protocol.md",
                mime="text/markdown",
                use_container_width=True
            )
        
        with col_dl3:
            # Create a printable version
            st.download_button(
                label="🖨️ Download for Printing",
                data=st.session_state.generated_protocol,
                file_name=f"{st.session_state.design['name']}_protocol_print.txt",
                mime="text/plain",
                use_container_width=True
            )
        
        st.markdown("---")
        
        # Protocol summary
        st.subheader("📊 Protocol Summary")
        
        col_sum1, col_sum2 = st.columns(2)
        
        with col_sum1:
            st.markdown("**Included Sections:**")
            st.markdown("""
            ✅ Formulation Overview
            ✅ Materials and Reagents
            ✅ Synthesis Protocol
            ✅ Characterization Methods
            ✅ In Vitro Studies
            ✅ In Vivo Studies (optional)
            ✅ Safety and Disposal
            ✅ Data Analysis
            ✅ Troubleshooting Guide
            """)
        
        with col_sum2:
            st.markdown("**Key Features:**")
            st.markdown("""
            🤖 AI-optimized procedures
            🔬 Material-specific methods
            📊 Quality control criteria
            ⚠️ Safety precautions
            🧪 Detailed step-by-step instructions
            📈 Data analysis guidelines
            🔧 Troubleshooting solutions
            📚 Reference suggestions
            """)
        
        st.info("💡 **Tip:** This protocol is AI-generated and should be reviewed and optimized for your specific laboratory conditions and equipment.")
    
    else:
        st.info("👆 Click **Generate Protocol** to create a comprehensive experimental protocol")
        
        with st.expander("ℹ️ About AI Protocol Generation"):
            st.markdown("""
            ### AI-Powered Protocol Generator
            
            The protocol generator uses advanced AI algorithms combined with established scientific literature to create customized experimental protocols for your nanoparticle formulation.
            
            **Features:**
            
            1. **Material-Specific Methods**
               - Synthesis protocols optimized for your chosen material
               - Appropriate reagents and equipment lists
               - Size and charge control strategies
            
            2. **Target-Adapted Procedures**
               - Biological assays relevant to your target tissue
               - Cell line recommendations
               - In vivo model suggestions
            
            3. **Comprehensive Coverage**
               - Complete material and equipment lists
               - Step-by-step synthesis instructions
               - Characterization protocols (DLS, TEM, zeta potential)
               - In vitro and in vivo testing procedures
               - Safety and disposal guidelines
               - Troubleshooting guides
            
            4. **Quality Control**
               - Acceptance criteria based on your design parameters
               - Statistical analysis guidelines
               - Documentation requirements
            
            5. **Regulatory Awareness**
               - Considers FDA/EMA guidelines
               - IACUC compliance notes
               - GLP considerations
            
            **How to Use:**
            
            1. Ensure your design parameters are finalized
            2. Select protocol type (comprehensive or focused)
            3. Enable AI suggestions for optimization tips
            4. Generate and review the protocol
            5. Download in your preferred format
            6. Customize for your specific laboratory
            
            **Important Notes:**
            
            - ⚠️ Always validate procedures in your laboratory
            - ⚠️ Obtain appropriate institutional approvals (IACUC, IRB, IBC)
            - ⚠️ Follow all safety regulations and guidelines
            - ⚠️ Consult with experienced researchers
            - ⚠️ Adapt protocols based on available equipment
            
            **AI Optimization:**
            
            The AI considers:
            - Physicochemical properties of your formulation
            - Target tissue characteristics
            - Payload type and stability requirements
            - Literature best practices
            - Regulatory requirements
            - Safety considerations
            """)
