"""Create a SANITIZED SAMPLE development database with fictional records.

WHY THIS EXISTS
---------------
The real databases are never shipped. Between them they hold bcrypt password
hashes for real accounts, 148 session token hashes, 213 authentication audit
rows with IP addresses and user agents, and medical-report assessment records.
None of that may travel in a source archive.

This script builds an equivalent database from the application's own SQLAlchemy
models — so the schema cannot drift from the code — and fills it with obviously
fictional records.

WHAT IT IS NOT
--------------
The output is NOT production data and must never be treated as such. Every
account is fictional, every password is the single documented demo password
below, and the file name says so loudly.

    Demo password for every seeded account: NanoBioSampleOnly-2026!

That password is documented on purpose: it is worthless. It unlocks nothing but
this throwaway file, and the file is regenerated by running this script.

USAGE
-----
    cd nanobio_studio_backend
    python scripts/seed_sample_database.py                  # writes ../<name>.db
    python scripts/seed_sample_database.py --output my.db   # or choose a path

To use it, point the backend at it:

    set AUTH_DATABASE_URL=sqlite+aiosqlite:///./nanobio_SAMPLE_DEV_DATABASE.db
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from sqlalchemy.ext.asyncio import (  # noqa: E402
    AsyncSession, async_sessionmaker, create_async_engine,
)

from nanobio_studio.app.core.security import hash_password  # noqa: E402
from nanobio_studio.app.db.base import Base  # noqa: E402
from nanobio_studio.app.db import auth_models  # noqa: E402,F401
from nanobio_studio.app.db import report_models  # noqa: E402,F401
from nanobio_studio.app.db import workspace_models  # noqa: E402,F401
from nanobio_studio.app.db.auth_models import User, UserRole  # noqa: E402
from nanobio_studio.app.db.workspace_models import (  # noqa: E402
    RecordOrigin, RunStatus, StoredRun, StudyPathway,
)

#: The single demo password. Documented deliberately — see the module docstring.
DEMO_PASSWORD = "NanoBioSampleOnly-2026!"

DEFAULT_NAME = "nanobio_SAMPLE_DEV_DATABASE_DO_NOT_USE_IN_PRODUCTION.db"

#: Fictional accounts. The names are obviously invented.
FICTIONAL_USERS = [
    ("sample.admin", "sample.admin@example.invalid", "Sample Administrator",
     UserRole.ADMIN),
    ("sample.researcher", "sample.researcher@example.invalid",
     "Sample Researcher", UserRole.RESEARCHER),
    ("sample.viewer", "sample.viewer@example.invalid", "Sample Viewer",
     UserRole.VIEWER),
]

#: A synthetic stored study. Inputs only plus a result shape — the numbers are
#: illustrative and were not produced by running the engines here.
SAMPLE_DESIGN_INPUTS = {
    "size_nm": 100.0, "charge_mv": -5.0, "encapsulation_percent": 85.0,
}


async def seed(output: Path) -> None:
    if output.exists():
        output.unlink()

    engine = create_async_engine(f"sqlite+aiosqlite:///{output.as_posix()}")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    maker = async_sessionmaker(engine, class_=AsyncSession,
                               expire_on_commit=False)
    now = datetime.now(timezone.utc)

    async with maker() as session:
        # --- fictional accounts --------------------------------------------
        # A real bcrypt hash of the documented demo password, so the sample
        # database actually works. It protects nothing.
        digest = hash_password(DEMO_PASSWORD)
        users = []
        for username, email, full_name, role in FICTIONAL_USERS:
            user = User(username=username, email=email, full_name=full_name,
                        password_hash=digest, role=role, is_active=True,
                        created_at=now - timedelta(days=30))
            session.add(user)
            users.append(user)
        await session.flush()

        # --- one synthetic stored study ------------------------------------
        # Deliberately BLOCKED: no engine ran to produce it, so it carries no
        # result. A seeded "complete" run would be a fabricated result.
        session.add(StoredRun(
            owner_id=users[1].id,
            name="Sample study — synthetic inputs, no engine run",
            origin=RecordOrigin.DEMO,
            pathway=StudyPathway.DEMO_SCENARIO,
            inputs_are_synthetic=True,
            disease="Breast Cancer",
            subtype="HER2-enriched (ER-, PR-, HER2+)",
            drug="Trastuzumab (Herceptin)",
            status=RunStatus.BLOCKED,
            design_inputs_json=str(SAMPLE_DESIGN_INPUTS).replace("'", '"'),
            design_result_json=None,
            pk_inputs_json=None,
            pk_result_json=None,
            engines_run="",
            engines_not_run=(
                "Design impact score\tSeeded sample; no engine was executed.\n"
                "Pharmacokinetic simulation\tSeeded sample; no engine was "
                "executed."),
            created_at=now - timedelta(days=1),
        ))

        # NOTE: no sessions, no audit rows, no report assessments are seeded.
        # Those tables hold token hashes, IP addresses and clinical documents in
        # the real database; an empty table is the honest sample.
        await session.commit()

    await engine.dispose()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a sanitized SAMPLE development database.")
    parser.add_argument("--output", default=None,
                        help=f"Output path (default: ../{DEFAULT_NAME})")
    args = parser.parse_args()

    output = (Path(args.output) if args.output
              else BACKEND_ROOT.parent / DEFAULT_NAME)
    asyncio.run(seed(output))

    print(f"Wrote sanitized sample database: {output}")
    print()
    print("  Accounts (all fictional):")
    for username, email, _, role in FICTIONAL_USERS:
        print(f"    {username:20} {role.value:12} {email}")
    print(f"  Password for every account: {DEMO_PASSWORD}")
    print()
    print("  This file is SAMPLE DATA. It contains no real user, no real")
    print("  patient information, no session tokens and no audit history.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
